# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0003_auto_20181022_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='profile_name',
        ),
        migrations.AddField(
            model_name='business',
            name='business_image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='neighbourhood_image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
